default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_trips_api_development

test:
  <<: *default
  database: rails_trips_api_test

production:
  <<: *default
  database: rails_trips_api_production
